/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.frontend;

/**
 *
 * @author luedu
 */
public class Prestamo extends javax.swing.JFrame {

    /**
     * Creates new form Prestamos
     */
    public Prestamo() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BExistente = new javax.swing.JButton();
        BNuevo1 = new javax.swing.JButton();
        BNuevo = new javax.swing.JButton();
        BBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BExistente.setBackground(new java.awt.Color(102, 255, 0));
        BExistente.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        BExistente.setText("Existente");
        BExistente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BExistenteActionPerformed(evt);
            }
        });
        getContentPane().add(BExistente, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 230, 50));

        BNuevo1.setBackground(new java.awt.Color(102, 255, 0));
        BNuevo1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        BNuevo1.setText("Cancelar");
        BNuevo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNuevo1ActionPerformed(evt);
            }
        });
        getContentPane().add(BNuevo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 230, 50));

        BNuevo.setBackground(new java.awt.Color(102, 255, 0));
        BNuevo.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        BNuevo.setText("Nuevo");
        BNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(BNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 230, 50));

        BBack.setBackground(new java.awt.Color(102, 255, 0));
        BBack.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        BBack.setText("Back");
        BBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBackActionPerformed(evt);
            }
        });
        getContentPane().add(BBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 230, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/5ab10d4485600a3d195f6753.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -60, 850, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BExistenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BExistenteActionPerformed
   
        this.setVisible(false);
        new Existente().setVisible(true);
        
    }//GEN-LAST:event_BExistenteActionPerformed

    private void BNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNuevoActionPerformed
        this.setVisible(false);
        new RegistroPrestamo().setVisible(true);
    }//GEN-LAST:event_BNuevoActionPerformed

    private void BBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBackActionPerformed
        this.setVisible(false);
        new Principal().setVisible(true);
    }//GEN-LAST:event_BBackActionPerformed

    private void BNuevo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNuevo1ActionPerformed
        this.setVisible(false);
        new EntregaLibro().setVisible(true);
    }//GEN-LAST:event_BNuevo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prestamo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BBack;
    private javax.swing.JButton BExistente;
    private javax.swing.JButton BNuevo;
    private javax.swing.JButton BNuevo1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
