/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.frontend;

/**
 *
 * @author luedu
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BPrestamo = new javax.swing.JButton();
        BRegistrar = new javax.swing.JButton();
        BReportes = new javax.swing.JButton();
        ButtonSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BPrestamo.setBackground(new java.awt.Color(102, 255, 0));
        BPrestamo.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        BPrestamo.setText("Préstamo");
        BPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPrestamoActionPerformed(evt);
            }
        });
        getContentPane().add(BPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 230, 50));

        BRegistrar.setBackground(new java.awt.Color(102, 255, 0));
        BRegistrar.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        BRegistrar.setText("Registrar");
        BRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(BRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 230, 50));

        BReportes.setBackground(new java.awt.Color(102, 255, 0));
        BReportes.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        BReportes.setText("Reportes");
        BReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BReportesActionPerformed(evt);
            }
        });
        getContentPane().add(BReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 230, 50));

        ButtonSalir.setBackground(new java.awt.Color(102, 255, 0));
        ButtonSalir.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        ButtonSalir.setText("Exit");
        ButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 230, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/5ab10d4485600a3d195f6753.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -60, 850, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPrestamoActionPerformed
        this.setVisible(false);
        new Prestamo().setVisible(true);
    }//GEN-LAST:event_BPrestamoActionPerformed

    private void BRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRegistrarActionPerformed
      this.setVisible(false);
        new Registro().setVisible(true);
    }//GEN-LAST:event_BRegistrarActionPerformed

    private void BReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BReportesActionPerformed
        this.setVisible(false);
        new Reporte().setVisible(true);
    }//GEN-LAST:event_BReportesActionPerformed

    private void ButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalirActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BPrestamo;
    private javax.swing.JButton BRegistrar;
    private javax.swing.JButton BReportes;
    private javax.swing.JButton ButtonSalir;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
