/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.frontend;

import javax.swing.JOptionPane;
import javax.swing.JTextField;

import com.backend.Libro;

/**
 *
 * @author luedu
 */
public class RegistroLibro extends javax.swing.JFrame {

    /**
     * Creates new form RegistroEstudiante
     */
    public RegistroLibro() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jlNickname = new javax.swing.JLabel();
        cajaTitulo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cajaAutor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cajaCodigoLibro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        botonGuardar = new javax.swing.JButton();
        cajaAnio = new javax.swing.JTextField();
        cajaMes = new javax.swing.JTextField();
        cajaDia = new javax.swing.JTextField();
        botonRegresar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        cajaEditorial = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cajaCopias = new javax.swing.JTextField();
        jLabelFont = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setBackground(new java.awt.Color(102, 255, 102));
        jLabelTitulo.setFont(new java.awt.Font("Arial Black", 0, 30)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 0, 0));
        jLabelTitulo.setText("Registro de Libros");
        jLabelTitulo.setAutoscrolls(true);
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));

        jlNickname.setBackground(new java.awt.Color(102, 255, 102));
        jlNickname.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jlNickname.setForeground(new java.awt.Color(51, 255, 51));
        jlNickname.setText("Titulo:");
        jlNickname.setAutoscrolls(true);
        getContentPane().add(jlNickname, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        cajaTitulo.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        cajaTitulo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaTitulo.setName("cajaTitulo"); // NOI18N
        cajaTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF1ActionPerformed(evt);
            }
        });
        getContentPane().add(cajaTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 370, 30));
        cajaTitulo.getAccessibleContext().setAccessibleName("cajaTitulo");
        cajaTitulo.getAccessibleContext().setAccessibleDescription("");

        jLabel7.setBackground(new java.awt.Color(102, 255, 102));
        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 255, 0));
        jLabel7.setText("Autor:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 190, -1));

        cajaAutor.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        cajaAutor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaAutor.setName("cajaAutor"); // NOI18N
        cajaAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF2ActionPerformed(evt);
            }
        });
        getContentPane().add(cajaAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 370, 30));

        jLabel8.setBackground(new java.awt.Color(102, 255, 102));
        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 255, 0));
        jLabel8.setText("ID Libro:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 220, -1));

        cajaCodigoLibro.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        cajaCodigoLibro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaCodigoLibro.setName("cajaCodigoLibro"); // NOI18N
        cajaCodigoLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF3ActionPerformed(evt);
            }
        });
        getContentPane().add(cajaCodigoLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 370, 30));

        jLabel4.setBackground(new java.awt.Color(102, 255, 102));
        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 255, 0));
        jLabel4.setText("Fecha de Publicación:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 280, -1));

        botonGuardar.setBackground(new java.awt.Color(102, 255, 102));
        botonGuardar.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        botonGuardar.setForeground(new java.awt.Color(255, 0, 51));
        botonGuardar.setText("Guardar");
        botonGuardar.setActionCommand("Ver Reportes");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        getContentPane().add(botonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 570, 140, -1));

        cajaAnio.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        cajaAnio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaAnio.setName("cajaAnio"); // NOI18N
        cajaAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF5ActionPerformed(evt);
            }
        });
        getContentPane().add(cajaAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 490, 90, 30));

        cajaMes.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        cajaMes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaMes.setName("cajaMes"); // NOI18N
        cajaMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF6ActionPerformed(evt);
            }
        });
        getContentPane().add(cajaMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 490, 70, 30));

        cajaDia.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        cajaDia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaDia.setName("cajaDia"); // NOI18N
        cajaDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF4ActionPerformed(evt);
            }
        });
        getContentPane().add(cajaDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 490, 70, 30));

        botonRegresar.setBackground(new java.awt.Color(102, 255, 102));
        botonRegresar.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        botonRegresar.setForeground(new java.awt.Color(255, 0, 51));
        botonRegresar.setText("Back");
        botonRegresar.setActionCommand("Ver Reportes");
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 580, 90, -1));

        jLabel9.setBackground(new java.awt.Color(102, 255, 102));
        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 255, 0));
        jLabel9.setText("Editorial:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 220, -1));

        cajaEditorial.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        cajaEditorial.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaEditorial.setName("cajaEditorial"); // NOI18N
        cajaEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF7ActionPerformed(evt);
            }
        });
        getContentPane().add(cajaEditorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 370, 30));

        jLabel10.setBackground(new java.awt.Color(102, 255, 102));
        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 255, 0));
        jLabel10.setText("Copias:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 220, -1));

        cajaCopias.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        cajaCopias.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaCopias.setName("cajaCopias"); // NOI18N
        cajaCopias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF8ActionPerformed(evt);
            }
        });
        getContentPane().add(cajaCopias, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 370, 30));

        jLabelFont.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/libros (2).jpg"))); // NOI18N
        getContentPane().add(jLabelFont, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF1ActionPerformed

    private void JTF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF2ActionPerformed

    private void JTF3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF3ActionPerformed

    private void JTF5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF5ActionPerformed

    private void JTF6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF6ActionPerformed

    private void JTF4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF4ActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        this.setVisible(false);
        new Registro().setVisible(true);

    }//GEN-LAST:event_BackActionPerformed

    private void JTF7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF7ActionPerformed

    private void JTF8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF8ActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        if(tieneCamposLlenos(cajaCodigoLibro, cajaAutor, cajaTitulo, cajaCopias)) {
            Libro b = new Libro();
            b.ingresarDatos(cajaCodigoLibro,cajaAutor,cajaTitulo,cajaCopias,cajaAnio,cajaMes,cajaDia,cajaEditorial);
            setVisible(false);
            new RegistroDeNuevosLibros().setVisible(true);
        }else {
	    JOptionPane.showMessageDialog(null, "Tiene que llenar los primeros cuatro campos", "Faltan datos", JOptionPane.INFORMATION_MESSAGE);
	}
    }//GEN-LAST:event_jButtonSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroLibro().setVisible(true);
            }
        });
    }
    
    private boolean tieneCamposLlenos(JTextField campo1, JTextField campo2, JTextField campo3, JTextField campo4) {
	return (campo1.getText()!="" & campo2.getText()!="" & campo3.getText()!="" & campo4.getText()!="");
    }

    private javax.swing.JButton botonRegresar;
    public static javax.swing.JTextField cajaTitulo;
    public static javax.swing.JTextField cajaAutor;
    public static javax.swing.JTextField cajaCodigoLibro;
    public static javax.swing.JTextField cajaDia;
    public static javax.swing.JTextField cajaAnio;
    public static javax.swing.JTextField cajaMes;
    public static javax.swing.JTextField cajaEditorial;
    public static javax.swing.JTextField cajaCopias;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFont;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jlNickname;
    // End of variables declaration//GEN-END:variables
}
