/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.frontend;

/**
 *
 * @author luedu
 */
public class Reporte extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Reporte() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BentregaHoy = new javax.swing.JButton();
        Bcarrera = new javax.swing.JButton();
        Bhistorial = new javax.swing.JButton();
        ButtonBack = new javax.swing.JButton();
        ButtonSalir1 = new javax.swing.JButton();
        BMora = new javax.swing.JButton();
        BEstudiante = new javax.swing.JButton();
        BRecaudacion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BentregaHoy.setBackground(new java.awt.Color(102, 255, 0));
        BentregaHoy.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        BentregaHoy.setText("Entrega Hoy");
        BentregaHoy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BentregaHoyActionPerformed(evt);
            }
        });
        getContentPane().add(BentregaHoy, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 230, 50));

        Bcarrera.setBackground(new java.awt.Color(102, 255, 0));
        Bcarrera.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        Bcarrera.setText("Por Carrera");
        Bcarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcarreraActionPerformed(evt);
            }
        });
        getContentPane().add(Bcarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 230, 50));

        Bhistorial.setBackground(new java.awt.Color(102, 255, 0));
        Bhistorial.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        Bhistorial.setText("Historial ");
        Bhistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BhistorialActionPerformed(evt);
            }
        });
        getContentPane().add(Bhistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 230, 50));

        ButtonBack.setBackground(new java.awt.Color(102, 255, 0));
        ButtonBack.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        ButtonBack.setText("Back");
        ButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBackActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 90, 50));

        ButtonSalir1.setBackground(new java.awt.Color(102, 255, 0));
        ButtonSalir1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        ButtonSalir1.setText("Exit");
        ButtonSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalir1ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonSalir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 390, 80, 50));

        BMora.setBackground(new java.awt.Color(102, 255, 0));
        BMora.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        BMora.setText("En Mora");
        BMora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMoraActionPerformed(evt);
            }
        });
        getContentPane().add(BMora, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 230, 50));

        BEstudiante.setBackground(new java.awt.Color(102, 255, 0));
        BEstudiante.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        BEstudiante.setText("Por Estudiante");
        BEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEstudianteActionPerformed(evt);
            }
        });
        getContentPane().add(BEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 230, 50));

        BRecaudacion.setBackground(new java.awt.Color(102, 255, 0));
        BRecaudacion.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        BRecaudacion.setText("Recaudación ");
        BRecaudacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRecaudacionActionPerformed(evt);
            }
        });
        getContentPane().add(BRecaudacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 230, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/5ab10d4485600a3d195f6753.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -60, 850, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BentregaHoyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BentregaHoyActionPerformed
        this.setVisible(false);
        new ReporteEntregaHoy().setVisible(true);
    }//GEN-LAST:event_BentregaHoyActionPerformed

    private void BcarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcarreraActionPerformed
        this.setVisible(false);
        new ReporteporCarrera().setVisible(true);
        
        /*
        Registro principa2 = new Registro();
        principa2.show();
        principa2.setVisible(false);

        G_Partidas principal = new G_Partidas();
        principal.show();
        this.setVisible(false);
        */
    }//GEN-LAST:event_BcarreraActionPerformed

    private void BhistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BhistorialActionPerformed
        this.setVisible(false);
        new ReporteporEstudiante().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_BhistorialActionPerformed

    private void ButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBackActionPerformed
        this.setVisible(false);
        new Principal().setVisible(true);
    }//GEN-LAST:event_ButtonBackActionPerformed

    private void ButtonSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalir1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ButtonSalir1ActionPerformed

    private void BMoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BMoraActionPerformed
        this.setVisible(false);
        new ReporteMora().setVisible(true);
    }//GEN-LAST:event_BMoraActionPerformed

    private void BEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEstudianteActionPerformed
        this.setVisible(false);
        new ReporteenCurso().setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_BEstudianteActionPerformed

    private void BRecaudacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRecaudacionActionPerformed
        this.setVisible(false);
        new ReporteRecaudacion().setVisible(true);
    }//GEN-LAST:event_BRecaudacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reporte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BEstudiante;
    private javax.swing.JButton BMora;
    private javax.swing.JButton BRecaudacion;
    private javax.swing.JButton Bcarrera;
    private javax.swing.JButton BentregaHoy;
    private javax.swing.JButton Bhistorial;
    private javax.swing.JButton ButtonBack;
    private javax.swing.JButton ButtonSalir1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
